# Generated by Django 6.1 on 2026-09-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ai_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='ai_plan_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='ai_review',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='ai_review_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
